version: '3.8'

services:
  webapp:
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # Volume for SSL certificates
    depends_on:
      - webapp