"""User model - age made a property

Revision ID: 135c97e98176
Revises: 58a0b5b71336
Create Date: 2025-06-22 10:56:34.106408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135c97e98176'
down_revision = '58a0b5b71336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
