"""User Model updated - more fields

Revision ID: 223d599ea92e
Revises: 01a3e5e6d79e
Create Date: 2025-05-22 22:47:49.293740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223d599ea92e'
down_revision = '01a3e5e6d79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=8), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('reset_time_limit', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_index('ix_user_reset_token', ['reset_token'], unique=True)
        batch_op.create_unique_constraint('uq_user_reset_token', ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_reset_token', type_='unique')
        batch_op.drop_index('ix_user_reset_token')
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('reset_time_limit')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
