"""Replace date_of_birth with age in User model

Revision ID: 58a0b5b71336
Revises: 2c4e7a7bd1fe
Create Date: 2025-06-21 11:09:52.270047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a0b5b71336'
down_revision = '2c4e7a7bd1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
