"""Plan model - is_for_self added

Revision ID: f4c7513422e1
Revises: 135c97e98176
Create Date: 2025-06-22 11:39:08.408717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c7513422e1'
down_revision = '135c97e98176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_for_self', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('is_for_self')

    # ### end Alembic commands ###
